### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by WaaaaaghBoss** [jjrscott/ColoredConsole#4]
![image](https://user-images.githubusercontent.com/11940269/65397750-35b7d480-dde5-11e9-834d-96e0fbadb82c.png)
xcod11

**Comment by WaaaaaghBoss** [comment]
How can I support Chinese?
![image](https://user-images.githubusercontent.com/11940269/65405449-ba6b1880-de0e-11e9-9bf8-f84c0fc66c51.png)

**Comment by jjrscott** [comment]
I've added installation instructions from #2.

**Comment by jjrscott** [comment]
What are the characters that failed to work? Can you add them as text to a comment?

**Comment by WaaaaaghBoss** [comment]
@jjrscott ？？？xcode characters？？？
![image](https://user-images.githubusercontent.com/11940269/65678585-273c1800-e086-11e9-98a4-b4376055c1e5.png)

iam not good at English

 "你好" is Simplified Chinese。

i have edit my color but run  ./colorify.pl   Will not generate ttf files

**Comment by WaaaaaghBoss** [comment]
![image](https://user-images.githubusercontent.com/11940269/65679813-6a978600-e088-11e9-95a5-ca5ba478c0ff.png)

How can I solve this problem?

**Comment by jjrscott** [comment]
Have you installed the font as per the instructions in the README?

**Comment by jjrscott** [comment]
It appears that the base font [Fira Mono](http://mozilla.github.io/Fira/) does not support Simplified Chinese characters. I'm sorry to say that creating new glyphs is outside the scope of what I can do for this project.

**Comment by WaaaaaghBoss** [comment]
@jjrscott 
this is my setup
![image](https://user-images.githubusercontent.com/11940269/65734677-b0932f00-e106-11e9-9e4f-d7fb103f0728.png)


The function of this project is very good. not support Simplified Chinese, it is also a good project.
The xcode console output is normal。
![image](https://user-images.githubusercontent.com/11940269/65734602-6316c200-e106-11e9-96a3-1adf77056182.png)

 I am using the "os_log_with_type" output, and the text output from console.app is wrong.
![image](https://user-images.githubusercontent.com/11940269/65734645-8b9ebc00-e106-11e9-9401-c45ac1875625.png)

should I block the "os_log_with_type" output in the release state? Just like in the release state, we need to shield "NSLog" to avoid excessive consumption of resources.

**Comment by jjrscott** [comment]
ColoredConsole only works in Xcode, it appears you can't set the font in Console.app. I think your suggestion is correct, don't use ⁠🏿 etc in `os_log` as it has its own types.
