### ISSUE TITLE
Works on simulator but tearing on device?

### ISSUE THREAD

**Issue by pwnified** [jjrscott/ColoredConsole#5]
On the simulator it works fine with anything I throw at it:
<img width="781" alt="Screen Shot 2019-11-22 at 15 45 53" src="https://user-images.githubusercontent.com/1249591/69468005-4f22c180-0d3f-11ea-844f-e62d95da223b.png">

But when running on a device (iPad mini):
<img width="816" alt="Screen Shot 2019-11-22 at 15 46 21" src="https://user-images.githubusercontent.com/1249591/69468029-6e215380-0d3f-11ea-8cdb-37a499cb1bb3.png">

It might just be a problem with Xcode's stdout stream not accounting for ligature sizes. Got any ideas, this is so close to being amazing.

**Comment by jjrscott** [comment]
I have changed the selection mechanism from Fitzpatrick Emoji Modifiers to Variation Selectors in da8f1032b0678e1e90ad44e3589f7529d1dd7f83. This appears to fix the problem and feels like what I should have used originally.
